# Storage directory
storage_directory = "db_files/"

# TCP socket to accept connections
tcp_socket = "127.0.0.1:7070"

# Max connection at a time
max_connections = 100

# Allowed values:
# - 1 => Info
# - 2 => Warn
# - 3 => Error
log_level = 1

# Signifies when database can do background merges of parts, depending on database load
background_merge_available_under = 30